name: compliance-check

on:
  repository_dispatch:
    types: [org-workflow-bot]

jobs:
  register-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: SvanBoxel/organization-workflow@1.3.0
        with:
          id: ${{ github.event.client_payload.id }}
          callback_url: ${{ github.event.client_payload.callback_url }}
          sha: ${{ github.event.client_payload.sha }}
          run_id: ${{ github.run_id }}
          name: ${{ github.workflow }} # Default: name of workflow. This name is shown with the check, but can be changed.

      - name: my-step
        run: echo "Hello World! from shared wf bot"